import enum

TICKRATE  = 60
TILE_SIZE = 32
GAME_MAP_FILE = "gamemap.txt"

WALL    = ' '
PELLET  = '.'
POWER_PELLET = 'o'
NOTHING = '#'
BARRIER = 'e'
INTERSECTION = 'x'
PELLET2 = INTERSECTION2 = 'X'

SPRITE_SHEET_FILE = "sprite-sheet.png"
SPRITE_SHEET_SPRITE_SIZE = 48
SPRITE_SHEET_SPRITE_SPACING = 8
SPRITE_SHEET_BLINKY_ROW = 1
SPRITE_SHEET_INKY_ROW   = 2
SPRITE_SHEET_PINKY_ROW  = 4
SPRITE_SHEET_CLYDE_ROW  = 3

ANIMATION_SPEED = 0.20

BACKGROUND_COLOR = (0, 0, 0)
WALL_COLOR    = (25, 25, 166)
PELLET_COLOR  = (222, 161, 133)
BARRIER_COLOR = (250, 142, 225)


class Direction(enum.IntEnum):
    RIGHT = 0
    UP    = 1
    LEFT  = 2
    DOWN  = 3
